//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payments.eway.RapidAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://au.ewaypayments.com/hotpotato", ConfigurationName="RapidAPI.RapidAPISoap")]
    public interface RapidAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://au.ewaypayments.com/hotpotato/CreateAccessCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        Payments.eway.RapidAPI.CreateAccessCodeResponse CreateAccessCode(Payments.eway.RapidAPI.CreateAccessCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://au.ewaypayments.com/hotpotato/GetAccessCodeResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseRequest))]
        Payments.eway.RapidAPI.GetAccessCodeResultResponse GetAccessCodeResult(Payments.eway.RapidAPI.GetAccessCodeResultRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class CreateAccessCodeRequest : BaseRequest {
        
        private Customer customerField;
        
        private CustomFields customFieldsField;
        
        private Payment paymentField;
        
        private ResponseMode responseModeField;
        
        private string redirectUrlField;
        
        private string iPAddressField;
        
        private string billingCountryField;
        
        private Method actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CustomFields CustomFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
                this.RaisePropertyChanged("CustomFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Payment Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("Payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ResponseMode ResponseMode {
            get {
                return this.responseModeField;
            }
            set {
                this.responseModeField = value;
                this.RaisePropertyChanged("ResponseMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RedirectUrl {
            get {
                return this.redirectUrlField;
            }
            set {
                this.redirectUrlField = value;
                this.RaisePropertyChanged("RedirectUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
                this.RaisePropertyChanged("IPAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BillingCountry {
            get {
                return this.billingCountryField;
            }
            set {
                this.billingCountryField = value;
                this.RaisePropertyChanged("BillingCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Method Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> tokenCustomerIDField;
        
        private bool tokenCustomerIDFieldSpecified;
        
        private bool saveTokenField;
        
        private string referenceField;
        
        private string titleField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string companyNameField;
        
        private string jobDescriptionField;
        
        private string street1Field;
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string emailField;
        
        private string phoneField;
        
        private string mobileField;
        
        private string commentsField;
        
        private string faxField;
        
        private string urlField;
        
        private string cardNumberField;
        
        private string cardNameField;
        
        private string cardExpiryMonthField;
        
        private string cardExpiryYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> TokenCustomerID {
            get {
                return this.tokenCustomerIDField;
            }
            set {
                this.tokenCustomerIDField = value;
                this.RaisePropertyChanged("TokenCustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TokenCustomerIDSpecified {
            get {
                return this.tokenCustomerIDFieldSpecified;
            }
            set {
                this.tokenCustomerIDFieldSpecified = value;
                this.RaisePropertyChanged("TokenCustomerIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool SaveToken {
            get {
                return this.saveTokenField;
            }
            set {
                this.saveTokenField = value;
                this.RaisePropertyChanged("SaveToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string JobDescription {
            get {
                return this.jobDescriptionField;
            }
            set {
                this.jobDescriptionField = value;
                this.RaisePropertyChanged("JobDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
                this.RaisePropertyChanged("Street1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("CardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CardName {
            get {
                return this.cardNameField;
            }
            set {
                this.cardNameField = value;
                this.RaisePropertyChanged("CardName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CardExpiryMonth {
            get {
                return this.cardExpiryMonthField;
            }
            set {
                this.cardExpiryMonthField = value;
                this.RaisePropertyChanged("CardExpiryMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CardExpiryYear {
            get {
                return this.cardExpiryYearField;
            }
            set {
                this.cardExpiryYearField = value;
                this.RaisePropertyChanged("CardExpiryYear");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class GetAccessCodeResultResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessCodeField;
        
        private string authorisationCodeField;
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        private string option1Field;
        
        private string option2Field;
        
        private string option3Field;
        
        private string invoiceNumberField;
        
        private string invoiceReferenceField;
        
        private System.Nullable<int> totalAmountField;
        
        private System.Nullable<int> transactionIDField;
        
        private System.Nullable<bool> transactionStatusField;
        
        private System.Nullable<long> tokenCustomerIDField;
        
        private bool tokenCustomerIDFieldSpecified;
        
        private System.Nullable<decimal> beagleScoreField;
        
        private bool beagleScoreFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessCode {
            get {
                return this.accessCodeField;
            }
            set {
                this.accessCodeField = value;
                this.RaisePropertyChanged("AccessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthorisationCode {
            get {
                return this.authorisationCodeField;
            }
            set {
                this.authorisationCodeField = value;
                this.RaisePropertyChanged("AuthorisationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
                this.RaisePropertyChanged("ResponseMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Option1 {
            get {
                return this.option1Field;
            }
            set {
                this.option1Field = value;
                this.RaisePropertyChanged("Option1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Option2 {
            get {
                return this.option2Field;
            }
            set {
                this.option2Field = value;
                this.RaisePropertyChanged("Option2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Option3 {
            get {
                return this.option3Field;
            }
            set {
                this.option3Field = value;
                this.RaisePropertyChanged("Option3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string InvoiceReference {
            get {
                return this.invoiceReferenceField;
            }
            set {
                this.invoiceReferenceField = value;
                this.RaisePropertyChanged("InvoiceReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("TotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> TransactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("TransactionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<long> TokenCustomerID {
            get {
                return this.tokenCustomerIDField;
            }
            set {
                this.tokenCustomerIDField = value;
                this.RaisePropertyChanged("TokenCustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TokenCustomerIDSpecified {
            get {
                return this.tokenCustomerIDFieldSpecified;
            }
            set {
                this.tokenCustomerIDFieldSpecified = value;
                this.RaisePropertyChanged("TokenCustomerIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> BeagleScore {
            get {
                return this.beagleScoreField;
            }
            set {
                this.beagleScoreField = value;
                this.RaisePropertyChanged("BeagleScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BeagleScoreSpecified {
            get {
                return this.beagleScoreFieldSpecified;
            }
            set {
                this.beagleScoreFieldSpecified = value;
                this.RaisePropertyChanged("BeagleScoreSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class CreateAccessCodeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessCodeField;
        
        private Customer customerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessCode {
            get {
                return this.accessCodeField;
            }
            set {
                this.accessCodeField = value;
                this.RaisePropertyChanged("AccessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class Payment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalAmountField;
        
        private string invoiceNumberField;
        
        private string invoiceDescriptionField;
        
        private string invoiceReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("TotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InvoiceDescription {
            get {
                return this.invoiceDescriptionField;
            }
            set {
                this.invoiceDescriptionField = value;
                this.RaisePropertyChanged("InvoiceDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string InvoiceReference {
            get {
                return this.invoiceReferenceField;
            }
            set {
                this.invoiceReferenceField = value;
                this.RaisePropertyChanged("InvoiceReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class CustomFields : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string option1Field;
        
        private string option2Field;
        
        private string option3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Option1 {
            get {
                return this.option1Field;
            }
            set {
                this.option1Field = value;
                this.RaisePropertyChanged("Option1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Option2 {
            get {
                return this.option2Field;
            }
            set {
                this.option2Field = value;
                this.RaisePropertyChanged("Option2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Option3 {
            get {
                return this.option3Field;
            }
            set {
                this.option3Field = value;
                this.RaisePropertyChanged("Option3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int customerIDField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAccessCodeResultRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateAccessCodeRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class BaseRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authenticationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Authentication Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public partial class GetAccessCodeResultRequest : BaseRequest {
        
        private string accessCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessCode {
            get {
                return this.accessCodeField;
            }
            set {
                this.accessCodeField = value;
                this.RaisePropertyChanged("AccessCode");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public enum ResponseMode {
        
        /// <remarks/>
        Redirect,
        
        /// <remarks/>
        Return,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://au.ewaypayments.com/hotpotato")]
    public enum Method {
        
        /// <remarks/>
        ProcessPayment,
        
        /// <remarks/>
        CreateTokenCustomer,
        
        /// <remarks/>
        UpdateTokenCustomer,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RapidAPISoapChannel : Payments.eway.RapidAPI.RapidAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RapidAPISoapClient : System.ServiceModel.ClientBase<Payments.eway.RapidAPI.RapidAPISoap>, Payments.eway.RapidAPI.RapidAPISoap {
        
        public RapidAPISoapClient() {
        }
        
        public RapidAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RapidAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RapidAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RapidAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Payments.eway.RapidAPI.CreateAccessCodeResponse CreateAccessCode(Payments.eway.RapidAPI.CreateAccessCodeRequest request) {
            return base.Channel.CreateAccessCode(request);
        }
        
        public Payments.eway.RapidAPI.GetAccessCodeResultResponse GetAccessCodeResult(Payments.eway.RapidAPI.GetAccessCodeResultRequest request) {
            return base.Channel.GetAccessCodeResult(request);
        }
    }
}
